// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createChunkStmt, err = db.PrepareContext(ctx, createChunk); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChunk: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteChunksByDocumentIDStmt, err = db.PrepareContext(ctx, deleteChunksByDocumentID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChunksByDocumentID: %w", err)
	}
	if q.deleteDocumentBySourcePathStmt, err = db.PrepareContext(ctx, deleteDocumentBySourcePath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDocumentBySourcePath: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.getDocumentBySourcePathStmt, err = db.PrepareContext(ctx, getDocumentBySourcePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetDocumentBySourcePath: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.listChunksByDocumentIDStmt, err = db.PrepareContext(ctx, listChunksByDocumentID); err != nil {
		return nil, fmt.Errorf("error preparing query ListChunksByDocumentID: %w", err)
	}
	if q.listMessagesStmt, err = db.PrepareContext(ctx, listMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessages: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.searchChunksByPrefixStmt, err = db.PrepareContext(ctx, searchChunksByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query SearchChunksByPrefix: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.upsertDocumentStmt, err = db.PrepareContext(ctx, upsertDocument); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertDocument: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createChunkStmt != nil {
		if cerr := q.createChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChunkStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteChunksByDocumentIDStmt != nil {
		if cerr := q.deleteChunksByDocumentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChunksByDocumentIDStmt: %w", cerr)
		}
	}
	if q.deleteDocumentBySourcePathStmt != nil {
		if cerr := q.deleteDocumentBySourcePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDocumentBySourcePathStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.getDocumentBySourcePathStmt != nil {
		if cerr := q.getDocumentBySourcePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDocumentBySourcePathStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.listChunksByDocumentIDStmt != nil {
		if cerr := q.listChunksByDocumentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listChunksByDocumentIDStmt: %w", cerr)
		}
	}
	if q.listMessagesStmt != nil {
		if cerr := q.listMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.searchChunksByPrefixStmt != nil {
		if cerr := q.searchChunksByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchChunksByPrefixStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.upsertDocumentStmt != nil {
		if cerr := q.upsertDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertDocumentStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	createChunkStmt                *sql.Stmt
	createMessageStmt              *sql.Stmt
	createSessionStmt              *sql.Stmt
	deleteChunksByDocumentIDStmt   *sql.Stmt
	deleteDocumentBySourcePathStmt *sql.Stmt
	deleteSessionStmt              *sql.Stmt
	getDocumentBySourcePathStmt    *sql.Stmt
	getSessionStmt                 *sql.Stmt
	listChunksByDocumentIDStmt     *sql.Stmt
	listMessagesStmt               *sql.Stmt
	listSessionsStmt               *sql.Stmt
	searchChunksByPrefixStmt       *sql.Stmt
	updateSessionStmt              *sql.Stmt
	upsertDocumentStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		createChunkStmt:                q.createChunkStmt,
		createMessageStmt:              q.createMessageStmt,
		createSessionStmt:              q.createSessionStmt,
		deleteChunksByDocumentIDStmt:   q.deleteChunksByDocumentIDStmt,
		deleteDocumentBySourcePathStmt: q.deleteDocumentBySourcePathStmt,
		deleteSessionStmt:              q.deleteSessionStmt,
		getDocumentBySourcePathStmt:    q.getDocumentBySourcePathStmt,
		getSessionStmt:                 q.getSessionStmt,
		listChunksByDocumentIDStmt:     q.listChunksByDocumentIDStmt,
		listMessagesStmt:               q.listMessagesStmt,
		listSessionsStmt:               q.listSessionsStmt,
		searchChunksByPrefixStmt:       q.searchChunksByPrefixStmt,
		updateSessionStmt:              q.updateSessionStmt,
		upsertDocumentStmt:             q.upsertDocumentStmt,
	}
}
