// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package db

import (
	"context"
)

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM drafts
WHERE session_id = ?
`

func (q *Queries) DeleteDraft(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteDraftStmt, deleteDraft, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDraft = `-- name: GetDraft :one
SELECT content
FROM drafts
WHERE session_id = ?
`

func (q *Queries) GetDraft(ctx context.Context, sessionID string) (string, error) {
	row := q.queryRow(ctx, q.getDraftStmt, getDraft, sessionID)
	var content string
	err := row.Scan(&content)
	return content, err
}

const upsertDraft = `-- name: UpsertDraft :exec
INSERT INTO drafts (session_id, content, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(session_id) DO UPDATE
SET content = excluded.content,
    updated_at = excluded.updated_at
`

type UpsertDraftParams struct {
	SessionID string `json:"session_id"`
	Content   string `json:"content"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertDraft(ctx context.Context, arg UpsertDraftParams) error {
	_, err := q.exec(ctx, q.upsertDraftStmt, upsertDraft, arg.SessionID, arg.Content, arg.UpdatedAt)
	return err
}
