// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, session_id, kind, provider, finished_at, is_compact_summary, message_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, kind, provider, finished_at, is_compact_summary, message_json
`

type CreateMessageParams struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Kind             string `json:"kind"`
	Provider         string `json:"provider"`
	FinishedAt       int64  `json:"finished_at"`
	IsCompactSummary int64  `json:"is_compact_summary"`
	MessageJson      string `json:"message_json"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Kind,
		arg.Provider,
		arg.FinishedAt,
		arg.IsCompactSummary,
		arg.MessageJson,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Provider,
		&i.FinishedAt,
		&i.IsCompactSummary,
		&i.MessageJson,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :execrows
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, kind, provider, finished_at, is_compact_summary, message_json
FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Provider,
		&i.FinishedAt,
		&i.IsCompactSummary,
		&i.MessageJson,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, kind, provider, finished_at, is_compact_summary, message_json
FROM messages
WHERE session_id = ?
ORDER BY finished_at ASC, id ASC
`

func (q *Queries) ListMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesStmt, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Kind,
			&i.Provider,
			&i.FinishedAt,
			&i.IsCompactSummary,
			&i.MessageJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
