// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Message struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Kind             string `json:"kind"`
	Provider         string `json:"provider"`
	FinishedAt       int64  `json:"finished_at"`
	IsCompactSummary int64  `json:"is_compact_summary"`
	MessageJson      string `json:"message_json"`
}

type Session struct {
	ID               string `json:"id"`
	ParentSessionID  string `json:"parent_session_id"`
	Title            string `json:"title"`
	MessageCount     int64  `json:"message_count"`
	CompletionTokens int64  `json:"completion_tokens"`
	CostMicros       int64  `json:"cost_micros"`
	SummaryMessageID string `json:"summary_message_id"`
	TodosJson        string `json:"todos_json"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}
