// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Chunk struct {
	ID         int64  `json:"id"`
	DocumentID int64  `json:"document_id"`
	ChunkIndex int64  `json:"chunk_index"`
	Content    string `json:"content"`
	Embedding  []byte `json:"embedding"`
}

type Document struct {
	ID             int64  `json:"id"`
	SourcePath     string `json:"source_path"`
	NormalizedPath string `json:"normalized_path"`
	FileHash       string `json:"file_hash"`
	UpdatedAt      int64  `json:"updated_at"`
}

type Message struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Kind             string `json:"kind"`
	Provider         string `json:"provider"`
	FinishedAt       int64  `json:"finished_at"`
	IsCompactSummary int64  `json:"is_compact_summary"`
	MessageJson      string `json:"message_json"`
}

type Session struct {
	ID               string `json:"id"`
	Title            string `json:"title"`
	MessageCount     int64  `json:"message_count"`
	CompletionTokens int64  `json:"completion_tokens"`
	CostMicros       int64  `json:"cost_micros"`
	SummaryMessageID string `json:"summary_message_id"`
	TodosJson        string `json:"todos_json"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type Task struct {
	SubagentSessionID   string         `json:"subagent_session_id"`
	ParentSessionID     string         `json:"parent_session_id"`
	Kind                string         `json:"kind"`
	Status              string         `json:"status"`
	InputPayloadJson    sql.NullString `json:"input_payload_json"`
	ProgressPayloadJson sql.NullString `json:"progress_payload_json"`
	ResultPayloadJson   sql.NullString `json:"result_payload_json"`
	ErrorMessage        string         `json:"error_message"`
	CreatedAt           int64          `json:"created_at"`
	CompletedAt         sql.NullInt64  `json:"completed_at"`
}
