// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteChunksByDocumentID(ctx context.Context, documentID int64) (int64, error)
	DeleteDocumentBySourcePath(ctx context.Context, sourcePath string) (int64, error)
	DeleteSession(ctx context.Context, id string) (int64, error)
	GetDocumentBySourcePath(ctx context.Context, sourcePath string) (Document, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListChunksByDocumentID(ctx context.Context, documentID int64) ([]Chunk, error)
	ListMessages(ctx context.Context, sessionID string) ([]Message, error)
	ListSessions(ctx context.Context) ([]Session, error)
	SearchChunksByPrefix(ctx context.Context, arg SearchChunksByPrefixParams) ([]SearchChunksByPrefixRow, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error)
}

var _ Querier = (*Queries)(nil)
