// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rag.sql

package db

import (
	"context"
)

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks (
    document_id,
    chunk_index,
    content,
    embedding
)
VALUES (?, ?, ?, ?)
RETURNING id, document_id, chunk_index, content, embedding
`

type CreateChunkParams struct {
	DocumentID int64  `json:"document_id"`
	ChunkIndex int64  `json:"chunk_index"`
	Content    string `json:"content"`
	Embedding  []byte `json:"embedding"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.queryRow(ctx, q.createChunkStmt, createChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
	)
	return i, err
}

const deleteChunksByDocumentID = `-- name: DeleteChunksByDocumentID :execrows
DELETE FROM chunks
WHERE document_id = ?
`

func (q *Queries) DeleteChunksByDocumentID(ctx context.Context, documentID int64) (int64, error) {
	result, err := q.exec(ctx, q.deleteChunksByDocumentIDStmt, deleteChunksByDocumentID, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentBySourcePath = `-- name: DeleteDocumentBySourcePath :execrows
DELETE FROM documents
WHERE source_path = ?
`

func (q *Queries) DeleteDocumentBySourcePath(ctx context.Context, sourcePath string) (int64, error) {
	result, err := q.exec(ctx, q.deleteDocumentBySourcePathStmt, deleteDocumentBySourcePath, sourcePath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocumentBySourcePath = `-- name: GetDocumentBySourcePath :one
SELECT id, source_path, normalized_path, file_hash, updated_at
FROM documents
WHERE source_path = ?
`

func (q *Queries) GetDocumentBySourcePath(ctx context.Context, sourcePath string) (Document, error) {
	row := q.queryRow(ctx, q.getDocumentBySourcePathStmt, getDocumentBySourcePath, sourcePath)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.NormalizedPath,
		&i.FileHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listChunksByDocumentID = `-- name: ListChunksByDocumentID :many
SELECT id, document_id, chunk_index, content, embedding
FROM chunks
WHERE document_id = ?
ORDER BY chunk_index ASC, id ASC
`

func (q *Queries) ListChunksByDocumentID(ctx context.Context, documentID int64) ([]Chunk, error) {
	rows, err := q.query(ctx, q.listChunksByDocumentIDStmt, listChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunksByPrefix = `-- name: SearchChunksByPrefix :many
SELECT
    c.id,
    c.document_id,
    c.chunk_index,
    c.content,
    c.embedding,
    d.id AS document_id_alias,
    d.source_path,
    d.normalized_path,
    d.file_hash,
    d.updated_at,
    vec_distance_cosine(c.embedding, ?1) AS distance
FROM chunks AS c
JOIN documents AS d
    ON d.id = c.document_id
WHERE d.normalized_path GLOB ?2
ORDER BY distance ASC, c.id ASC
LIMIT ?3
`

type SearchChunksByPrefixParams struct {
	QueryEmbedding     interface{} `json:"query_embedding"`
	NormalizedPathGlob string      `json:"normalized_path_glob"`
	TopK               int64       `json:"top_k"`
}

type SearchChunksByPrefixRow struct {
	ID              int64       `json:"id"`
	DocumentID      int64       `json:"document_id"`
	ChunkIndex      int64       `json:"chunk_index"`
	Content         string      `json:"content"`
	Embedding       []byte      `json:"embedding"`
	DocumentIDAlias int64       `json:"document_id_alias"`
	SourcePath      string      `json:"source_path"`
	NormalizedPath  string      `json:"normalized_path"`
	FileHash        string      `json:"file_hash"`
	UpdatedAt       int64       `json:"updated_at"`
	Distance        interface{} `json:"distance"`
}

func (q *Queries) SearchChunksByPrefix(ctx context.Context, arg SearchChunksByPrefixParams) ([]SearchChunksByPrefixRow, error) {
	rows, err := q.query(ctx, q.searchChunksByPrefixStmt, searchChunksByPrefix, arg.QueryEmbedding, arg.NormalizedPathGlob, arg.TopK)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchChunksByPrefixRow{}
	for rows.Next() {
		var i SearchChunksByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.DocumentIDAlias,
			&i.SourcePath,
			&i.NormalizedPath,
			&i.FileHash,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
    source_path,
    normalized_path,
    file_hash,
    updated_at
)
VALUES (?, ?, ?, ?)
ON CONFLICT(source_path) DO UPDATE
SET normalized_path = excluded.normalized_path,
    file_hash = excluded.file_hash,
    updated_at = excluded.updated_at
RETURNING id, source_path, normalized_path, file_hash, updated_at
`

type UpsertDocumentParams struct {
	SourcePath     string `json:"source_path"`
	NormalizedPath string `json:"normalized_path"`
	FileHash       string `json:"file_hash"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.queryRow(ctx, q.upsertDocumentStmt, upsertDocument,
		arg.SourcePath,
		arg.NormalizedPath,
		arg.FileHash,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.NormalizedPath,
		&i.FileHash,
		&i.UpdatedAt,
	)
	return i, err
}
