// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, title, created_at, updated_at, last_active_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, created_at, updated_at, last_active_at
`

type CreateSessionParams struct {
	ID           string `json:"id"`
	Title        string `json:"title"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
	LastActiveAt int64  `json:"last_active_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastActiveAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, title, created_at, updated_at, last_active_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, created_at, updated_at, last_active_at
FROM sessions
ORDER BY last_active_at DESC, created_at DESC, id DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET title = ?, updated_at = ?, last_active_at = ?
WHERE id = ?
RETURNING id, title, created_at, updated_at, last_active_at
`

type UpdateSessionParams struct {
	Title        string `json:"title"`
	UpdatedAt    int64  `json:"updated_at"`
	LastActiveAt int64  `json:"last_active_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.UpdatedAt,
		arg.LastActiveAt,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
