// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    completion_tokens,
    cost_micros,
    summary_message_id,
    todos_json,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, parent_session_id, title, message_count, completion_tokens, cost_micros, summary_message_id, todos_json, created_at, updated_at
`

type CreateSessionParams struct {
	ID               string `json:"id"`
	ParentSessionID  string `json:"parent_session_id"`
	Title            string `json:"title"`
	MessageCount     int64  `json:"message_count"`
	CompletionTokens int64  `json:"completion_tokens"`
	CostMicros       int64  `json:"cost_micros"`
	SummaryMessageID string `json:"summary_message_id"`
	TodosJson        string `json:"todos_json"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.CompletionTokens,
		arg.CostMicros,
		arg.SummaryMessageID,
		arg.TodosJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.CompletionTokens,
		&i.CostMicros,
		&i.SummaryMessageID,
		&i.TodosJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, parent_session_id, title, message_count, completion_tokens, cost_micros, summary_message_id, todos_json, created_at, updated_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.CompletionTokens,
		&i.CostMicros,
		&i.SummaryMessageID,
		&i.TodosJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, completion_tokens, cost_micros, summary_message_id, todos_json, created_at, updated_at
FROM sessions
ORDER BY updated_at DESC, created_at DESC, id DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.CompletionTokens,
			&i.CostMicros,
			&i.SummaryMessageID,
			&i.TodosJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET parent_session_id = ?,
    title = ?,
    message_count = ?,
    completion_tokens = ?,
    cost_micros = ?,
    summary_message_id = ?,
    todos_json = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, completion_tokens, cost_micros, summary_message_id, todos_json, created_at, updated_at
`

type UpdateSessionParams struct {
	ParentSessionID  string `json:"parent_session_id"`
	Title            string `json:"title"`
	MessageCount     int64  `json:"message_count"`
	CompletionTokens int64  `json:"completion_tokens"`
	CostMicros       int64  `json:"cost_micros"`
	SummaryMessageID string `json:"summary_message_id"`
	TodosJson        string `json:"todos_json"`
	UpdatedAt        int64  `json:"updated_at"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.CompletionTokens,
		arg.CostMicros,
		arg.SummaryMessageID,
		arg.TodosJson,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.CompletionTokens,
		&i.CostMicros,
		&i.SummaryMessageID,
		&i.TodosJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
