// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'complete',
    result_payload_json = ?,
    completed_at = ?
WHERE subagent_session_id = ?
RETURNING subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
`

type CompleteTaskParams struct {
	ResultPayloadJson sql.NullString `json:"result_payload_json"`
	CompletedAt       sql.NullInt64  `json:"completed_at"`
	SubagentSessionID string         `json:"subagent_session_id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.completeTaskStmt, completeTask, arg.ResultPayloadJson, arg.CompletedAt, arg.SubagentSessionID)
	var i Task
	err := row.Scan(
		&i.SubagentSessionID,
		&i.ParentSessionID,
		&i.Kind,
		&i.Status,
		&i.InputPayloadJson,
		&i.ProgressPayloadJson,
		&i.ResultPayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    subagent_session_id,
    parent_session_id,
    kind,
    status,
    input_payload_json,
    progress_payload_json,
    result_payload_json,
    error_message,
    created_at,
    completed_at
)
VALUES (?, ?, ?, 'running', ?, ?, ?, ?, ?, NULL)
RETURNING subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
`

type CreateTaskParams struct {
	SubagentSessionID   string         `json:"subagent_session_id"`
	ParentSessionID     string         `json:"parent_session_id"`
	Kind                string         `json:"kind"`
	InputPayloadJson    sql.NullString `json:"input_payload_json"`
	ProgressPayloadJson sql.NullString `json:"progress_payload_json"`
	ResultPayloadJson   sql.NullString `json:"result_payload_json"`
	ErrorMessage        string         `json:"error_message"`
	CreatedAt           int64          `json:"created_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.SubagentSessionID,
		arg.ParentSessionID,
		arg.Kind,
		arg.InputPayloadJson,
		arg.ProgressPayloadJson,
		arg.ResultPayloadJson,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.SubagentSessionID,
		&i.ParentSessionID,
		&i.Kind,
		&i.Status,
		&i.InputPayloadJson,
		&i.ProgressPayloadJson,
		&i.ResultPayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :one
UPDATE tasks
SET status = 'failed',
    error_message = ?,
    completed_at = ?
WHERE subagent_session_id = ?
RETURNING subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
`

type FailTaskParams struct {
	ErrorMessage      string        `json:"error_message"`
	CompletedAt       sql.NullInt64 `json:"completed_at"`
	SubagentSessionID string        `json:"subagent_session_id"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.failTaskStmt, failTask, arg.ErrorMessage, arg.CompletedAt, arg.SubagentSessionID)
	var i Task
	err := row.Scan(
		&i.SubagentSessionID,
		&i.ParentSessionID,
		&i.Kind,
		&i.Status,
		&i.InputPayloadJson,
		&i.ProgressPayloadJson,
		&i.ResultPayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
FROM tasks
WHERE subagent_session_id = ?
`

func (q *Queries) GetTask(ctx context.Context, subagentSessionID string) (Task, error) {
	row := q.queryRow(ctx, q.getTaskStmt, getTask, subagentSessionID)
	var i Task
	err := row.Scan(
		&i.SubagentSessionID,
		&i.ParentSessionID,
		&i.Kind,
		&i.Status,
		&i.InputPayloadJson,
		&i.ProgressPayloadJson,
		&i.ResultPayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTasksByParentSession = `-- name: ListTasksByParentSession :many
SELECT subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
FROM tasks
WHERE parent_session_id = ?
ORDER BY created_at ASC, subagent_session_id ASC
`

func (q *Queries) ListTasksByParentSession(ctx context.Context, parentSessionID string) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByParentSessionStmt, listTasksByParentSession, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.SubagentSessionID,
			&i.ParentSessionID,
			&i.Kind,
			&i.Status,
			&i.InputPayloadJson,
			&i.ProgressPayloadJson,
			&i.ResultPayloadJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskProgress = `-- name: UpdateTaskProgress :one
UPDATE tasks
SET progress_payload_json = ?
WHERE subagent_session_id = ?
RETURNING subagent_session_id, parent_session_id, kind, status, input_payload_json, progress_payload_json, result_payload_json, error_message, created_at, completed_at
`

type UpdateTaskProgressParams struct {
	ProgressPayloadJson sql.NullString `json:"progress_payload_json"`
	SubagentSessionID   string         `json:"subagent_session_id"`
}

func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskProgressStmt, updateTaskProgress, arg.ProgressPayloadJson, arg.SubagentSessionID)
	var i Task
	err := row.Scan(
		&i.SubagentSessionID,
		&i.ParentSessionID,
		&i.Kind,
		&i.Status,
		&i.InputPayloadJson,
		&i.ProgressPayloadJson,
		&i.ResultPayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
